name: CICD

on: push

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install maui workloads
        run: dotnet workload install maui-android maui-ios maui-maccatalyst
      - name: Install dependencies
        run: dotnet restore --source https://api.nuget.org/v3/index.json 
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal --filter "FullyQualifiedName~UnitTests" -p:CollectCoverage=true -p:CoverletOutputFormat="json%2copencover" -p:CoverletOutput="../coverage" -p:MergeWith="../coverage.json" -c Release --no-build devoctomy.Passchamp.sln
      - name: Code Coverage
        uses: codecov/codecov-action@v1
        with:
          files: coverage.opencover.xml
          commit_parent: $(git rev-parse --short "$GITHUB_SHA")
          fail_ci_if_error: true
          verbose: false
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: '/a/passchamp/passchamp/devoctomy.Passchamp.Client/bin/'