name: Unit Tests & Code Coverage

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:

  unit-tests:
    name: Unit Tests
    runs-on: windows-2022
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Install maui workloads
        run: dotnet workload install maui-android maui-ios maui-maccatalyst
      - name: Install dependencies
        run: dotnet restore --source https://api.nuget.org/v3/index.json 
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal --filter "FullyQualifiedName~UnitTests" -p:CollectCoverage=true -p:CoverletOutputFormat="json%2copencover" -p:CoverletOutput="../coverage" -p:MergeWith="../coverage.json" -c Release --no-build devoctomy.Passchamp.sln
      - name: Code Coverage
        uses: codecov/codecov-action@v1
        with:
          files: coverage.opencover.xml
          commit_parent: $(git rev-parse --short "$GITHUB_SHA")
          fail_ci_if_error: true
          verbose: false
          
  security-scan:
    name: Security Scan
    needs: unit-tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          output: results.sarif
          format: sarif
          # Adjust severity of non-security issues
          gh-code-scanning-compat: true
          # Force 0 exit code to allow SARIF file generation
          # This will handover control about PR rejection to the GitHub side
          max-allowed-issues: 2147483647
      
      # Upload the SARIF file generated in the previous step
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: results.sarif
          
  build-windows:
    name: Windows Build
    needs: security-scan
    runs-on: windows-2022
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-prerelease: true

      - name: Install MAUI Workloads
        run: |
          dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore devoctomy.Passchamp.Client/devoctomy.Passchamp.Client.csproj

      - name: Build MAUI Windows
        run: dotnet build devoctomy.Passchamp.Client/devoctomy.Passchamp.Client.csproj -c Release -f net6.0-windows10.0.19041.0 --no-restore

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: windows-ci-build
          path: devoctomy.Passchamp.Client/bin/Release/net6.0-windows*/**/*.msix

  build-android:
    name: Android Build
    needs: security-scan
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - uses: actions/setup-java@v2
        with:
          distribution: 'microsoft'
          java-version: '11'

      - name: Install MAUI Workloads
        run: |
          dotnet workload install android --ignore-failed-sources
          dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore devoctomy.Passchamp.Client/devoctomy.Passchamp.Client.csproj

      - name: Build MAUI Android
        run: dotnet build devoctomy.Passchamp.Client/devoctomy.Passchamp.Client.csproj -c Release -f net6.0-android --no-restore

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: android-ci-build
          path: devoctomy.Passchamp.Client/bin/Release/net6.0-android/*Signed.a*

  build-ios:
    name: iOS Build
    needs: security-scan
    runs-on: macos-11
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - name: Install MAUI Workloads
        run: |
          dotnet workload install ios --ignore-failed-sources
          dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore devoctomy.Passchamp.Client/devoctomy.Passchamp.Client.csproj

      - name: Build MAUI iOS
        run: dotnet build devoctomy.Passchamp.Client/devoctomy.Passchamp.Client.csproj -c Release -f net6.0-ios --no-restore

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: ios-ci-build
          path: devoctomy.Passchamp.Client/bin/Release/net6.0-ios/**/*.app/

  build-mac:
    name: MacCatalyst Build
    needs: security-scan
    runs-on: macos-11
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - name: Install MAUI Workloads
        run: |
          dotnet workload install maccatalyst --ignore-failed-sources
          dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore devoctomy.Passchamp.Client/devoctomy.Passchamp.Client.csproj

      - name: Build MAUI MacCatalyst
        run: dotnet build devoctomy.Passchamp.Client/devoctomy.Passchamp.Client.csproj -c Release -f net6.0-maccatalyst --no-restore

      - name: Upload MacCatalyst Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: macos-ci-build
          path: devoctomy.Passchamp.Client/bin/Release/net6.0-maccatalyst/**/*.app/